### ISSUE TITLE
erro ao tentar rodar o programa.

### ISSUE THREAD

**Issue by giovannism20** [lucasmoura/funk_generator#1]
```
[$user@$user funk_generator]$ chmod a+x app.py 
[$user@$user funk_generator]$ ./app.py 
./app.py: linha 4: from: comando não encontrado
./app.py: linha 5: from: comando não encontrado
./app.py: linha 7: from: comando não encontrado
./app.py: linha 8: from: comando não encontrado
./app.py: linha 11: erro de sintaxe próximo ao token inesperado `('
./app.py: linha 11: `app = Flask(__name__)'
```

**Comment by lucasmoura** [comment]
Eu vou subir hoje mesmo um arquivo readme explicando como rodar o programa e um requirements.txt explicando quais são as dependências do projeto.

Entretanto, se vc quiser só rodar a aplicação de fato, sugiro usar o container que criei, o nome dele é
lucasmoura/funk-generator. Basta dar um docker pull e depois um docker run nele fazendo o bind na porta 5000 que vai funcionar perfeitamente.

**Comment by lucasmoura** [comment]
Pronto, acabei de subir o readme do projeto.
